export const COUNTRIES = [
  'Argentina',
  'Bolivia',
  'Brasil',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Ecuador',
  'El Salvador',
  'España',
  'Guatemala',
  'Honduras',
  'México',
  'Nicaragua',
  'Panamá',
  'Paraguay',
  'Perú',
  'Puerto Rico',
  'República Dominicana',
  'Uruguay',
  'Venezuela',
  'Estados Unidos',
  'Canadá',
  'Francia',
  'Italia',
  'Portugal',
  'Reino Unido',
  'Alemania',
  'Otros'
];

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  'Argentina': [
    'Buenos Aires',
    'Córdoba',
    'Rosario',
    'Mendoza',
    'La Plata',
    'San Miguel de Tucumán',
    'Mar del Plata',
    'Salta',
    'Santa Fe',
    'San Juan',
    'Resistencia',
    'Neuquén',
    'Santiago del Estero',
    'Corrientes',
    'Posadas',
    'Bahía Blanca',
    'Paraná',
    'Formosa',
    'San Luis',
    'La Rioja',
    'Catamarca',
    'Río Gallegos',
    'Ushuaia',
    'San Salvador de Jujuy',
    'Santa Rosa',
    'Rawson',
    'Viedma'
  ],
  'España': [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Sevilla',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma',
    'Las Palmas de Gran Canaria',
    'Bilbao',
    'Alicante',
    'Córdoba',
    'Valladolid',
    'Vigo',
    'Gijón',
    'Hospitalet de Llobregat',
    'A Coruña',
    'Vitoria-Gasteiz',
    'Granada',
    'Elche',
    'Oviedo',
    'Badalona',
    'Cartagena',
    'Terrassa',
    'Jerez de la Frontera',
    'Sabadell',
    'Móstoles',
    'Santa Cruz de Tenerife',
    'Pamplona',
    'Almería',
    'Alcalá de Henares',
    'Fuenlabrada',
    'Donostia-San Sebastián',
    'Leganés',
    'Santander',
    'Burgos',
    'Castellón de la Plana',
    'Alcorcón',
    'Albacete',
    'Getafe'
  ],
  'México': [
    'Ciudad de México',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Tijuana',
    'León',
    'Juárez',
    'Torreón',
    'Querétaro',
    'San Luis Potosí',
    'Mérida',
    'Mexicali',
    'Aguascalientes',
    'Cuernavaca',
    'Saltillo',
    'Hermosillo',
    'Culiacán',
    'Chihuahua',
    'Morelia',
    'Tampico',
    'Xalapa',
    'Reynosa',
    'Toluca',
    'Veracruz',
    'Villahermosa',
    'Irapuato',
    'Mazatlán',
    'Nuevo Laredo',
    'Tuxtla Gutiérrez',
    'Acapulco'
  ],
  'Colombia': [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Cúcuta',
    'Bucaramanga',
    'Pereira',
    'Santa Marta',
    'Ibagué',
    'Pasto',
    'Manizales',
    'Neiva',
    'Villavicencio',
    'Armenia',
    'Valledupar',
    'Montería',
    'Sincelejo',
    'Popayán',
    'Buenaventura'
  ],
  'Chile': [
    'Santiago',
    'Valparaíso',
    'Concepción',
    'La Serena',
    'Antofagasta',
    'Temuco',
    'Rancagua',
    'Talca',
    'Arica',
    'Chillán',
    'Iquique',
    'Los Ángeles',
    'Puerto Montt',
    'Calama',
    'Copiapó',
    'Osorno',
    'Quillota',
    'Valdivia',
    'Punta Arenas',
    'San Antonio'
  ],
  'Perú': [
    'Lima',
    'Arequipa',
    'Trujillo',
    'Chiclayo',
    'Piura',
    'Iquitos',
    'Cusco',
    'Huancayo',
    'Chimbote',
    'Pucallpa',
    'Tacna',
    'Ica',
    'Juliaca',
    'Sullana',
    'Ayacucho',
    'Chincha Alta',
    'Huánuco',
    'Tarapoto',
    'Puno',
    'Tumbes'
  ],
  'Brasil': [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Goiânia',
    'Belém',
    'Porto Alegre',
    'Guarulhos',
    'Campinas',
    'São Luís',
    'São Gonçalo',
    'Maceió',
    'Duque de Caxias',
    'Natal',
    'Teresina'
  ],
  'Venezuela': [
    'Caracas',
    'Maracaibo',
    'Valencia',
    'Barquisimeto',
    'Maracay',
    'Ciudad Guayana',
    'San Cristóbal',
    'Maturín',
    'Ciudad Bolívar',
    'Cumana',
    'Mérida',
    'Barcelona',
    'Turmero',
    'Cabimas',
    'Santa Teresa del Tuy',
    'Barinas',
    'Punto Fijo',
    'Los Teques',
    'Acarigua',
    'Carúpano'
  ],
  'Ecuador': [
    'Quito',
    'Guayaquil',
    'Cuenca',
    'Santo Domingo',
    'Machala',
    'Durán',
    'Manta',
    'Portoviejo',
    'Loja',
    'Ambato',
    'Esmeraldas',
    'Quevedo',
    'Riobamba',
    'Milagro',
    'Ibarra',
    'La Libertad',
    'Babahoyo',
    'Sangolquí',
    'Daule',
    'El Carmen'
  ],
  'Bolivia': [
    'Santa Cruz de la Sierra',
    'La Paz',
    'Cochabamba',
    'Sucre',
    'Oruro',
    'Tarija',
    'Potosí',
    'Sacaba',
    'Quillacollo',
    'Trinidad',
    'Riberalta',
    'Cobija',
    'Yacuiba',
    'Warnes',
    'Montero',
    'Llallagua',
    'Tupiza',
    'Camiri',
    'Villamontes',
    'Bermejo'
  ],
  'Uruguay': [
    'Montevideo',
    'Salto',
    'Paysandú',
    'Las Piedras',
    'Rivera',
    'Maldonado',
    'Tacuarembó',
    'Melo',
    'Mercedes',
    'Artigas',
    'Minas',
    'San José de Mayo',
    'Durazno',
    'Florida',
    'Barros Blancos',
    'Ciudad de la Costa',
    'Treinta y Tres',
    'Rocha',
    'San Carlos',
    'Pando'
  ],
  'Paraguay': [
    'Asunción',
    'Ciudad del Este',
    'San Lorenzo',
    'Luque',
    'Capiatá',
    'Lambaré',
    'Fernando de la Mora',
    'Limpio',
    'Ñemby',
    'Encarnación',
    'Mariano Roque Alonso',
    'Pedro Juan Caballero',
    'Coronel Oviedo',
    'Concepción',
    'Villa Elisa',
    'Villarrica',
    'Itauguá',
    'Caaguazú',
    'Paraguarí',
    'Caacupé'
  ]
};

export const MEDICAL_SPECIALTIES = [
  'Anestesiología',
  'Cardiología',
  'Cirugía General',
  'Cirugía Cardiovascular',
  'Cirugía Plástica',
  'Dermatología',
  'Endocrinología',
  'Gastroenterología',
  'Geriatría',
  'Ginecología y Obstetricia',
  'Hematología',
  'Infectología',
  'Medicina de Emergencia',
  'Medicina Familiar',
  'Medicina Interna',
  'Nefrología',
  'Neumología',
  'Neurología',
  'Neurocirugía',
  'Oftalmología',
  'Oncología',
  'Ortopedia y Traumatología',
  'Otorrinolaringología',
  'Patología',
  'Pediatría',
  'Psiquiatría',
  'Radiología',
  'Reumatología',
  'Urología',
  'Medicina Nuclear',
  'Medicina del Trabajo',
  'Medicina Deportiva',
  'Medicina Legal',
  'Anatomía Patológica',
  'Microbiología',
  'Inmunología',
  'Genética Médica',
  'Medicina Preventiva',
  'Salud Pública',
  'Otra'
];

export const getCitiesForCountry = (country: string): string[] => {
  return CITIES_BY_COUNTRY[country] || ['Otra'];
};